[book]
authors = ["Dave Henthorn"]
language = "en"
multilingual = false
src = "src"
title = "The CTF Handbook"

[build]
build-dir = "docs"  
create-missing = false 

[output.html]
mathjax-support = true
preferred-dark-theme = "navy"
site-url = "/ctfbook/"
